global:
  scrape_interval: 15s
  evaluation_interval: 15s

# для remote write
# читсо напоминание с временными метками реши возникшую ху..ню
#remote_write:
#  - url: http://localhost:9090/api/v1/write


# сбор метрик самого Prom
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# сбор системных
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

#  - job_name: 'k6'
#    static_configs:
#      - targets: ['k6-dashboard:6565']

    # А - альтернатива
    # сбор метрик Influx
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: /metrics
    scrape_interval: 10s